DB_PATH                 = 'maindatabase'  #путь к БД, в том числе удалённой
EXCEL_TEMPLATE_PATH     = "C:\MHAD\zayavka.docx"#путь сохранения
EXCEL_HEADER_ROWS       = 5#настройка для openpyxl
MAIN_REPORT_PAGE        = 'Отчет'#настройка для openpyxl
WRAP_COLUMNS            = ['is_conditions_good', 'specie']#wrap pandas
SAVE_DIR                = "C:\MHAD\zaya.docx"#шаблон документа
NAMES_TXT_PATH          = 'names.txt'
DATABASE_DRIVER_QT      = 'QSQLITE'  #Для движка QT
DATABASE_DRIVER_PANDAS  = 'sqlite'   #для движка пандаса